# WandB log
project: toymodel_project

# Model structure definition
trainer:
  type: toymodel
  diffusion:
    type: GMFlow
    input_type: image
    denoising:
      type: GMFlowMLP2DDenoiser
      num_gaussians: 64
    flow_loss:
      type: GMFlowNLLLoss
      log_cfgs:
        type: quartile
        prefix_name: loss_trans
        total_timesteps: 1000
      data_info:
        pred_means: means
        target: x_t_low
        pred_logstds: logstds
        pred_logweights: logweights
    denoising_mean_mode: U
    timestep_sampler:
      type: continuous
      shift: 1.0
      logit_normal_enable: False
      num_timesteps: 1000
    diffusion_use_ema: True
    noise_sampler:
      type: "gaussian"

test_cfg:
  output_mode: sample
  sampler: GMFlowSDE
  num_timesteps: 8
  order: 2

# Training related parameters
train:
  epochs: 100
  lr: 1e-5
  weight_decay: 0.0
  optimizer: adamw
  scheduler: cosine             # Optional: constant, step, cosine
  accumulation_steps: 2
  clip_grad: 1.0
  warmup_steps: 500
  eval_interval: 5
  output_dir: outputs
  save_checkpoint: false
  save_interval: 10  
  resume_checkpoint: false
  resume_from: outputs/toymodel_exp/20250608_2116/checkpoint_100.pt

test:
  n_samples: 1e6
  out_path: outputs

# Data configuration
data:
  train:
    type: CheckerboardData
    n_rc: 8
    n_samples: 1e8
    thickness: 1.0
    scale: 8.0
    shift: [0.0, 0.0]
    rotation: 0.0
  train_dataloader:
    num_workers: 4
    batch_size: 4096
    persistent_workers: false
    pin_memory: false

# Mixed precision control
fp16: true

# Optional flags
debug: true
