# WandB log
project: shapenetpart_seg

# Model structure definition
trainer:
  type: shapenetpart_seg
  diffusion:
    type: GMFlow
    input_type: point_cloud
    embedding:
      type: xxx
      num_classes: 50
      embed_dim: 2048
      pc_embed_dim: 2048
    denoising:
      type: GMFlowMLPLabelDenoiser
      num_gaussians: 32
      embed_dim: 2048
    flow_loss:
      type: GMFlowNLLLoss
      log_cfgs:
        type: quartile
        prefix_name: loss_trans
        total_timesteps: 1000
      data_info:
        pred_means: means
        target: x_t_low
        pred_logstds: logstds
        pred_logweights: logweights
    denoising_mean_mode: U
    timestep_sampler:
      type: continuous
      shift: 1.0
      logit_normal_enable: False
      num_timesteps: 1000
    diffusion_use_ema: True
    noise_sampler:
      type: "gaussian"

test_cfg:
  output_mode: sample
  sampler: GMFlowSDE
  num_timesteps: 8
  order: 2

# Training related parameters
train:
  epochs: 100
  lr: 1e-5
  weight_decay: 0.0
  optimizer: adamw
  scheduler: cosine             # Optional: constant, step, cosine
  accumulation_steps: 2
  clip_grad: 1.0
  warmup_steps: 500
  val_interval: 1
  output_dir: outputs/shapenetpart_seg_exp
  save_checkpoint: true
  save_interval: 10  
  resume_checkpoint: false
  resume_from: outputs/shapenetpart_seg_exp/20250608_1552/checkpoint_10.pt

test:
  n_samples: 1e6
  out_path: outputs/shapenetpart_seg_exp/test_samples.png

# Data configuration
data:
  train:
    type: ShapeNetPart
    root: /ssdArray/hongyou/dev/data/shapenet
    dataset_name: shapenetpart
    num_points: 2048
    split: train
    load_name: True
    load_file: True
    segmentation: True
    random_rotate: False
    random_jitter: False
    random_translate: False
  train_dataloader:
    num_workers: 4
    batch_size: 64
    persistent_workers: true
    pin_memory: true
  val:
    type: ShapeNetPart
    root: /ssdArray/hongyou/dev/data/shapenet
    dataset_name: shapenetpart
    num_points: 2048
    split: val
    load_name: True
    load_file: True
    segmentation: True
    random_rotate: False
    random_jitter: False
    random_translate: False
  val_dataloader:
    num_workers: 4
    batch_size: 32
    persistent_workers: false
    pin_memory: false

# Mixed precision control
fp16: true

# Optional flags
debug: true
