method: shapenetpart_seg

# WandB log
project: shapenetpart_seg

# Model structure definition
model:
  type: GMFlow
  denoising:
    type: GMFlowMLPLabelDenoiser
    num_gaussians: 64
    num_classes: 50
  flow_loss:
    type: GMFlowNLLLoss
    log_cfgs:
      type: quartile
      prefix_name: loss_trans
      total_timesteps: 1000
    data_info:
      pred_means: means
      target: x_t_low
      pred_logstds: logstds
      pred_logweights: logweights
  test_cfg:
    output_mode: sample
    sampler: GMFlowSDE
    num_timesteps: 8
    order: 2
  denoising_mean_mode: U
  timestep_sampler:
    type: continuous
    shift: 1.0
    logit_normal_enable: False
    num_timesteps: 1000
  diffusion_use_ema: True

  noise_sampler:
    type: "gaussian"

# Training related parameters
train:
  batch_size: 4096
  epochs: 20
  lr: 1e-5
  weight_decay: 0.0
  optimizer: adam
  scheduler: cosine             # Optional: constant, step, cosine
  accumulation_steps: 2
  clip_grad: 1.0
  warmup_steps: 500
  eval_interval: 5
  output_dir: outputs/toymodel_exp
  save_checkpoint: true
  save_interval: 1000
  
test:
  n_samples: 1e6
  out_path: outputs/toymodel_exp/test_samples.png

# Data configuration
data:
  train:
    type: ShapeNetPart
    root: /ssdArray/hongyou/dev/data/shapenet
    dataset_name: shapenetpart
    num_points: 2048
    split: train
    load_name: True
    load_file: True
    segmentation: True
    random_rotate: False
    random_jitter: False
    random_translate: False
  train_dataloader:
    num_workers: 4
    batch_size: 1024
    persistent_workers: true
    pin_memory: true
  val:
    type: ShapeNetPart
    root: /ssdArray/hongyou/dev/data/shapenet
    dataset_name: shapenetpart
    num_points: 2048
    split: val
    load_name: True
    load_file: True
    segmentation: True
    random_rotate: False
    random_jitter: False
    random_translate: False
  val_dataloader:
    num_workers: 4
    batch_size: 1024
    persistent_workers: true
    pin_memory: true

# Mixed precision control
fp16: true

# Optional flags
debug: true
